name: Como usar variavel de ambiente e contexto do GitHub Actions
on: 
  push:
      branches: [main]
env:
  ENV_WORKFLOW: "Valor WORKFLOW"
jobs:
  contextos-job:
    runs-on: ubuntu-latest
    env:
        ENV_JOB: "Valor JOB CONTEXT"
    steps:
      - name: Pegando ref
        env:
          GITHUB_CONTEXT_REF: ${{ github.ref }}
        run: echo "$GITHUB_CONTEXT_REF"
      - name: Pegando SHA do commit
        env:
          GITHUB_CONTEXT_SHA: ${{ github.sha }}
        run: echo "$GITHUB_CONTEXT_SHA"
      - name: Contexto github
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Contexto env
        env:
          ENV_CONTEXT: ${{ toJson(env) }}
        run: echo "$ENV_CONTEXT"
      - name: Contexto job
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Contexto steps
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Contexto runner
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Contexto vars
        env:
          RUNNER_VARS: ${{ toJson(vars) }}
        run: echo "$RUNNER_VARS"
      - name: Acessando vars direto
        run: echo "${{ vars.VARS_XPTO }}"
      - name: Contexto secrets
        env:
          RUNNER_SECRETS: ${{ toJson(secrets) }}
        run: echo "$RUNNER_SECRETS"
      - name: Acessando secret direto
        run: echo "${{ secrets.SECRET_XPTO }}"
